### ISSUE TITLE
Serializing array of strings in API requests

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/explorer#2015]
API specifies
https://github.com/oasisprotocol/nexus/blob/389cc9f2e08d0b0d0252b8594a2efe218e5fb5e4/api/spec/v1.yaml#L1274-L1277
```
          style: form
          explode: false
          schema:
            type: array
```

https://github.com/oasisprotocol/explorer/pull/2012 manually added `paramsSerializer: paramSerializerWithComma`

Ideally this should be fixed at orval config level (or even upstream) based on API definition, not manually

(related https://github.com/oasisprotocol/explorer/issues/1839)

**Comment by csillag** [comment]
Some relevant documentation is at https://orval.dev/reference/configuration/output#paramsserializer

**Comment by csillag** [comment]
To quote the [full definition in the API spec](https://github.com/oasisprotocol/nexus/blob/389cc9f2e08d0b0d0252b8594a2efe218e5fb5e4/api/spec/v1.yaml#L1274-L1281):

``` 
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
            maxItems: 6
          description: A filter on the name of the ROFL app. If multiple names are provided, the ROFL App must match all of them.

```

It would be nice if Orval could also the `maxItems` information, at least in a comment if nothing else.
